title: Diogo Santos Design
author: Diogo Santos
email: diogossantos@outlook.com
description: > # this means to ignore newlines until "exclude"
  Olá! Chamo-me Diogo Santos, tenho 26 anos de idade e sou brasileiro, de Florianópolis, Santa Catarina. Estou em Portugal desde Setembro de 2017, quando iniciei meus estudos de intercâmbio no IADE - Universidade Europeia. Depois de um ano, concluí meus estudos de Graduação no Brasil, ao mesmo tempo que finalizei as aulas no IADE. Estudei principalmente as áreas de Design Gráfico, Branding e Web Design. Atualmente estou a especializar-me em digital experience design, com foco para aárea de User Experience Design.

baseurl: /diogossantos

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%b %-d, %Y"

# generate social links in footer
social_links:
  twitter: diogossantos
  github:  diogossantos
  facebook: diogossantos
